name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: dotnet restore src/fiap-catalog-service.sln
        
      - name: Compilar aplicação
        run: dotnet build --configuration Release

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Executar testes
        run: dotnet test --no-build --verbosity normal

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Preparar artefato para deploy
        run: |
          zip -r deploy.zip . -x "*.git*"

      - name: Deploy no AWS Lambda
        run: |
          aws lambda update-function-code \
          --function-name fiap-catalog-service \
          --zip-file fileb://deploy.zip
